version: '3.8'

services:
  # Serviço do Banco de Dados
  postgres:
    image: postgres:16
    container_name: wallet-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ${POSTGRES_DB:-wallet_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Healthcheck: Avisa o Docker quando o banco está REALMENTE pronto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-wallet_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço da Sua Aplicação Java
  app:
    build: .  # Procura o Dockerfile na pasta atual
    container_name: wallet-api
    ports:
      - "${APP_PORT:-8081}:8080" # Mapeia a porta 8080 do container para 8081 do seu PC
    environment:
      # Conecta usando o nome do serviço 'postgres', não 'localhost'
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-wallet_db}
      DB_USER: ${POSTGRES_USER:-admin}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-123}
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    depends_on:
      postgres:
        condition: service_healthy # Só inicia o Java quando o Healthcheck do banco der OK
    # Healthcheck da aplicação: Garante que a API está respondendo
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - wallet-network

volumes:
  postgres_data:

networks:
  wallet-network:
    driver: bridge